version: "3.0"

services:
  moviebackend:
    build: Server/
    image: movieapp/backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - moviedb
    expose:
      - "8080"
      - "9090"
    networks:
      - backend
  moviedb:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  moviefrontend:
    build: .
    image: movieapp/frontend
    depends_on:
      - moviebackend
    networks:
      - backend
  loadbalancer:
    build: nginx/
    image: movieapp/loadbalancer
    depends_on:
      - moviefrontend
    ports:
      - "8080:80"
    networks:
      - backend
networks:
  backend:
