version: "3.0"

services:
  moviebackend:
    build: .
    image: movieapp/backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - moviedb
    ports:
      - 8080:8080
    networks:
      - backend
  moviedb:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
networks:
  backend:
